//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mi9TESTDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class brnstock
    {
        public string branchcode { get; set; }
        public int varint { get; set; }
        public Nullable<int> lastmovedate { get; set; }
        public int onorder { get; set; }
        public double avcost { get; set; }
        public decimal retail { get; set; }
        public decimal showroom { get; set; }
        public decimal damaged { get; set; }
        public decimal allocated { get; set; }
        public decimal quarantine { get; set; }
        public string stockcheck { get; set; }
        public Nullable<int> lastcheckdte { get; set; }
        public short discrepancy { get; set; }
        public Nullable<double> stdcost { get; set; }
        public Nullable<double> lastcost { get; set; }
        public Nullable<double> carryoverqty { get; set; }
        public Nullable<double> carryovercst { get; set; }
        public Nullable<System.DateTime> firstdeldate { get; set; }
        public Nullable<System.DateTime> lastdeldate { get; set; }
        public Nullable<System.DateTime> FirstSoldDate { get; set; }
        public Nullable<System.DateTime> LastSoldDate { get; set; }
        public decimal CrossDockQty { get; set; }
        public decimal TransferHeldQty { get; set; }
    
        public virtual branch branch { get; set; }
        public virtual productcode productcode { get; set; }
    }
}
