//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mi9TESTDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class btranscount
    {
        public int transint { get; set; }
        public int transline { get; set; }
        public short sequenceno { get; set; }
        public Nullable<short> transcount { get; set; }
        public Nullable<int> linecount { get; set; }
        public Nullable<int> transunits { get; set; }
        public Nullable<decimal> transvalue { get; set; }
        public Nullable<decimal> transtax { get; set; }
        public int notepad { get; set; }
    }
}
