//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mi9TESTDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class btransifdata
    {
        public int transint { get; set; }
        public int transline { get; set; }
        public short status { get; set; }
        public int notepad { get; set; }
        public string transdata { get; set; }
    }
}
