//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mi9TESTDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class consigdoc
    {
        public string warehouse { get; set; }
        public string consignment { get; set; }
        public short levelid { get; set; }
        public string processname { get; set; }
    
        public virtual consighdr consighdr { get; set; }
    }
}
