//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mi9TESTDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mi9_mms_fs_trainEntities : DbContext
    {
        public mi9_mms_fs_trainEntities()
            : base("name=mi9_mms_fs_trainEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<branch> branches { get; set; }
        public virtual DbSet<brnstkchk> brnstkchks { get; set; }
        public virtual DbSet<brnstock> brnstocks { get; set; }
        public virtual DbSet<btranscount> btranscounts { get; set; }
        public virtual DbSet<btransdisc> btransdiscs { get; set; }
        public virtual DbSet<btranshdr> btranshdrs { get; set; }
        public virtual DbSet<btransifdata> btransifdatas { get; set; }
        public virtual DbSet<btransline> btranslines { get; set; }
        public virtual DbSet<consigdest> consigdests { get; set; }
        public virtual DbSet<consighdr> consighdrs { get; set; }
        public virtual DbSet<consigline> consiglines { get; set; }
        public virtual DbSet<pricechghdr> pricechghdrs { get; set; }
        public virtual DbSet<proddesc> proddescs { get; set; }
        public virtual DbSet<productcode> productcodes { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<purchcost> purchcosts { get; set; }
        public virtual DbSet<purchorder> purchorders { get; set; }
        public virtual DbSet<purchordline> purchordlines { get; set; }
        public virtual DbSet<reasoncode> reasoncodes { get; set; }
        public virtual DbSet<supplier> suppliers { get; set; }
        public virtual DbSet<supproduct> supproducts { get; set; }
        public virtual DbSet<supprodunit> supprodunits { get; set; }
        public virtual DbSet<varcode> varcodes { get; set; }
        public virtual DbSet<consigdoc> consigdocs { get; set; }
        public virtual DbSet<purchordhist> purchordhists { get; set; }
        public virtual DbSet<prodkey> prodkeys { get; set; }
        public virtual DbSet<structlevel> structlevels { get; set; }
        public virtual DbSet<TOFS_RetailPrice> TOFS_RetailPrice { get; set; }
    }
}
