//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mi9TESTDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchordhist
    {
        public int transint { get; set; }
        public string buyer { get; set; }
        public Nullable<int> suppbrint { get; set; }
        public string seasoncode { get; set; }
        public System.DateTime orderdate { get; set; }
        public string location { get; set; }
        public Nullable<System.DateTime> deliverydate { get; set; }
        public Nullable<System.DateTime> canceldate { get; set; }
        public string ackreference { get; set; }
        public Nullable<System.DateTime> ackdate { get; set; }
        public Nullable<int> plint { get; set; }
        public Nullable<double> settlement { get; set; }
        public string settletype { get; set; }
        public string buyingmethod { get; set; }
        public Nullable<double> currrate { get; set; }
        public string printprice { get; set; }
        public string openorder { get; set; }
        public Nullable<int> splint { get; set; }
        public Nullable<System.DateTime> amenddate { get; set; }
        public string amenduser { get; set; }
    }
}
