//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mi9TESTDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOFS_RetailPrice
    {
        public int Varint { get; set; }
        public Nullable<decimal> Retail_Price { get; set; }
        public string Price_List { get; set; }
    }
}
