//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PICountDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pi_count_stores
    {
        public int id { get; set; }
        public Nullable<int> list_id { get; set; }
        public string storeid { get; set; }
        public Nullable<int> sku_list_id { get; set; }
        public Nullable<bool> isCompleted { get; set; }
    }
}
