//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PICountDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pi_count
    {
        public int rowid { get; set; }
        public string list_name { get; set; }
        public Nullable<System.DateTime> date_create { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> expexted_count_date { get; set; }
    }
}
