//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PICountDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_product_count
    {
        public int RowId { get; set; }
        public string store_id { get; set; }
        public Nullable<System.DateTime> dateTime_created { get; set; }
        public string sku { get; set; }
        public Nullable<int> sku_counted_qty { get; set; }
        public string list_name { get; set; }
        public string user_id { get; set; }
        public string reason_code { get; set; }
        public Nullable<bool> isWriteOff { get; set; }
        public Nullable<bool> isAdHoc { get; set; }
        public Nullable<bool> isPiCount { get; set; }
        public Nullable<bool> isCompleted { get; set; }
    }
}
