//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuditDataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class auditEntities : DbContext
    {
        public auditEntities()
            : base("name=auditEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_audit_api> tbl_audit_api { get; set; }
        public virtual DbSet<tbl_PICount_Audit> tbl_PICount_Audit { get; set; }
        public virtual DbSet<tbl_ADHOCCount_Audit> tbl_ADHOCCount_Audit { get; set; }
        public virtual DbSet<tbl_SupplierToStore_Audit> tbl_SupplierToStore_Audit { get; set; }
        public virtual DbSet<tbl_WarehouseToStore_Audit> tbl_WarehouseToStore_Audit { get; set; }
        public virtual DbSet<tbl_goodsout_audit> tbl_goodsout_audit { get; set; }
        public virtual DbSet<tbl_InterStore_Audit> tbl_InterStore_Audit { get; set; }
        public virtual DbSet<tbl_authentication_audit> tbl_authentication_audit { get; set; }
        public virtual DbSet<tbl_SupplierMassAccept_Audit> tbl_SupplierMassAccept_Audit { get; set; }
        public virtual DbSet<tbl_cancel_allocations_audit> tbl_cancel_allocations_audit { get; set; }
        public virtual DbSet<tbl_PP_frontend_audit> tbl_PP_frontend_audit { get; set; }
        public virtual DbSet<tbl_writeoff_audit> tbl_writeoff_audit { get; set; }
    }
}
