//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mi9TESTDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class consigdest
    {
        public string warehouse { get; set; }
        public string consignment { get; set; }
        public string desttype { get; set; }
        public string destination { get; set; }
        public int condestint { get; set; }
        public string delroute { get; set; }
        public Nullable<int> droppoint { get; set; }
        public string destdoc { get; set; }
        public string delroutedoc { get; set; }
        public string payterms { get; set; }
        public Nullable<double> freightchg { get; set; }
        public Nullable<decimal> freighttax { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string address3 { get; set; }
        public string address4 { get; set; }
        public string postcode { get; set; }
        public string country { get; set; }
        public int notepad { get; set; }
        public string status { get; set; }
        public string reference { get; set; }
        public string category { get; set; }
        public string reasoncode { get; set; }
        public string reference2 { get; set; }
        public Nullable<int> KitAssemblyOrderDestinationID { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public string ShipUser { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public string ReceiveUser { get; set; }
        public byte AllocStatus { get; set; }
        public byte PickStatus { get; set; }
        public Nullable<int> ParcelCnt { get; set; }
        public string ParcelType { get; set; }
        public Nullable<System.DateTime> DateInterfaced { get; set; }
        public decimal ShippingCost { get; set; }
        public byte RTVDisposalMethod { get; set; }
        public int SourceSubLocationID { get; set; }
        public string UserCancelled { get; set; }
        public Nullable<System.DateTime> DateCancelled { get; set; }
        public string UserReopened { get; set; }
        public Nullable<System.DateTime> DateReopened { get; set; }
        public byte[] RowVer { get; set; }
        public Nullable<int> VendorLocationID { get; set; }
        public string ShipMethodCode { get; set; }
        public string ShipMethodCodeGLU { get; set; }
        public string ShipReference { get; set; }
        public string DriverReference { get; set; }
        public string TruckNumber { get; set; }
        public string UserRejected { get; set; }
        public Nullable<System.DateTime> DateRejected { get; set; }
        public string UserApproved { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public System.DateTime DateLastModified { get; set; }
        public Nullable<System.DateTime> DateCreatedInStore { get; set; }
        public string UserCreatedInStore { get; set; }
        public Nullable<System.DateTime> DateCancelledInStore { get; set; }
        public string UserCancelledInStore { get; set; }
        public string StoreSuggestionCode { get; set; }
        public Nullable<System.DateTime> DateAmendedInStore { get; set; }
        public string UserAmendedInStore { get; set; }
        public Nullable<System.DateTime> DateApprovedInStore { get; set; }
        public string UserApprovedInStore { get; set; }
        public Nullable<System.DateTime> DateShippedInStore { get; set; }
        public string UserShippedInStore { get; set; }
        public Nullable<int> ParentShipDestID { get; set; }
        public Nullable<int> LastChildShipCodeSuffix { get; set; }
        public Nullable<System.DateTime> DateReceivedInStore { get; set; }
        public string UserReceivedInStore { get; set; }
    
        public virtual consighdr consighdr { get; set; }
    }
}
