//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mi9DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class branch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public branch()
        {
            this.branches1 = new HashSet<branch>();
            this.brnstocks = new HashSet<brnstock>();
            this.btranshdrs = new HashSet<btranshdr>();
            this.btranshdrs1 = new HashSet<btranshdr>();
            this.brnstats = new HashSet<brnstat>();
        }
    
        public string branchcode { get; set; }
        public string colevel1 { get; set; }
        public string colevel2 { get; set; }
        public string colevel3 { get; set; }
        public string name { get; set; }
        public string shortname { get; set; }
        public string commsline { get; set; }
        public string mastind { get; set; }
        public string mastbranch { get; set; }
        public string league { get; set; }
        public Nullable<int> positionind { get; set; }
        public string branchtype { get; set; }
        public Nullable<int> branchsize { get; set; }
        public string locntype { get; set; }
        public string storegroup { get; set; }
        public Nullable<short> staff { get; set; }
        public Nullable<short> floors { get; set; }
        public Nullable<short> lifts { get; set; }
        public string catalogue { get; set; }
        public string tradplan { get; set; }
        public string holplan { get; set; }
        public string merchplan { get; set; }
        public string repsource { get; set; }
        public Nullable<short> reptype { get; set; }
        public string delroute { get; set; }
        public string status { get; set; }
        public string operstatus { get; set; }
        public int notepad { get; set; }
        public Nullable<System.DateTime> auditdate { get; set; }
        public Nullable<System.DateTime> stkchkdate { get; set; }
        public Nullable<System.DateTime> opendate { get; set; }
        public Nullable<System.DateTime> closedate { get; set; }
        public System.DateTime createdate { get; set; }
        public Nullable<System.DateTime> amenddate { get; set; }
        public Nullable<System.DateTime> deletedate { get; set; }
        public string integritylok { get; set; }
        public int levint { get; set; }
        public string version { get; set; }
        public string commsmethod { get; set; }
        public string keydatelist { get; set; }
        public string bankcode { get; set; }
        public string languageid { get; set; }
        public string pricegroup { get; set; }
        public string franchisee { get; set; }
        public string replenmethod { get; set; }
        public string sizegrade { get; set; }
        public Nullable<System.DateTime> grandopendte { get; set; }
        public Nullable<System.DateTime> remodeldate { get; set; }
        public Nullable<System.DateTime> plandate { get; set; }
        public string printloc { get; set; }
        public string costcentre { get; set; }
        public string autoreplen { get; set; }
        public Nullable<int> SaleGoalProfileID { get; set; }
        public decimal CommissionPercent { get; set; }
        public string ba01 { get; set; }
        public string ba02 { get; set; }
        public string ba03 { get; set; }
        public string ba04 { get; set; }
        public string ba05 { get; set; }
        public string ba06 { get; set; }
        public string ba07 { get; set; }
        public string ba08 { get; set; }
        public string ba09 { get; set; }
        public string ba10 { get; set; }
        public string ba11 { get; set; }
        public string ba12 { get; set; }
        public string ba13 { get; set; }
        public string ba14 { get; set; }
        public string ba15 { get; set; }
        public string ba16 { get; set; }
        public string ba17 { get; set; }
        public string ba18 { get; set; }
        public string ba19 { get; set; }
        public string ba20 { get; set; }
        public string ba21 { get; set; }
        public string ba22 { get; set; }
        public string ba23 { get; set; }
        public string ba24 { get; set; }
        public string ba25 { get; set; }
        public string GLEntity { get; set; }
        public string GLCompany { get; set; }
        public string GLCorpCostCentre { get; set; }
        public byte Comparative { get; set; }
        public Nullable<decimal> ShrinkPercent { get; set; }
        public string CoLevel4 { get; set; }
        public string CoLevel5 { get; set; }
        public Nullable<int> AltCoHierarchy1ID { get; set; }
        public string Currency { get; set; }
        public string BankCode1 { get; set; }
        public string BankAccount1 { get; set; }
        public string GLForBankCode1 { get; set; }
        public string BankCode2 { get; set; }
        public string BankAccount2 { get; set; }
        public string GLForBankCode2 { get; set; }
        public Nullable<int> SellingSize { get; set; }
        public Nullable<int> BackRoomSize { get; set; }
        public string ShoppingCenter1 { get; set; }
        public string ShoppingCenter2 { get; set; }
        public string BuildingType { get; set; }
        public string CeilingType { get; set; }
        public Nullable<decimal> CeilingHeight { get; set; }
        public Nullable<int> HVACUnits { get; set; }
        public bool LoadingDock { get; set; }
        public bool DelRestrictions { get; set; }
        public bool HoldTruckReceipt { get; set; }
        public string FireLine1 { get; set; }
        public string FireLine2 { get; set; }
        public Nullable<System.DateTime> LeaseCommenceDate { get; set; }
        public Nullable<System.DateTime> PossessionPerLeaseDate { get; set; }
        public Nullable<System.DateTime> LeaseExpirationDate { get; set; }
        public Nullable<System.DateTime> RelocationDate1 { get; set; }
        public Nullable<System.DateTime> RelocationDate2 { get; set; }
        public Nullable<System.DateTime> RelocationDate3 { get; set; }
        public Nullable<System.DateTime> RelocationDate4 { get; set; }
        public bool ChangeInSameMall { get; set; }
        public Nullable<decimal> OpeningCash { get; set; }
        public string InventoryManagedAtWarehouseCode { get; set; }
        public bool SingleDestinationPO { get; set; }
        public bool ShipInCartons { get; set; }
        public Nullable<System.DateTime> DateStartReplen { get; set; }
        public Nullable<System.DateTime> DateEndReplen { get; set; }
        public bool TransInHomeCurrency { get; set; }
        public short LeadTime { get; set; }
        public bool ReplSunday { get; set; }
        public bool ReplMonday { get; set; }
        public bool ReplTuesday { get; set; }
        public bool ReplWednesday { get; set; }
        public bool ReplThursday { get; set; }
        public bool ReplFriday { get; set; }
        public bool ReplSaturday { get; set; }
        public bool TaxIncluded { get; set; }
        public string Planogram { get; set; }
        public string PlanogramGLU { get; set; }
        public string FAInvoiceAccount { get; set; }
        public string FACostAccount { get; set; }
        public string FAWriteOffAccount { get; set; }
        public bool FAInvoiceUseCorp { get; set; }
        public bool FACostUseCorp { get; set; }
        public bool FAWriteOffUseCorp { get; set; }
        public byte ChannelType { get; set; }
        public string UPSAccount { get; set; }
        public bool EmailHouseCoEntry { get; set; }
        public bool EmailCorpCoEntry { get; set; }
        public bool EmailHouseCoShip { get; set; }
        public bool EmailCorpCoShip { get; set; }
        public bool EmailHouseCoReturn { get; set; }
        public bool EmailCorpCoReturn { get; set; }
        public bool PrimaryForManagedAtWarehouse { get; set; }
        public int POSTransNumber { get; set; }
        public string MarketCode { get; set; }
        public string MarketGLU { get; set; }
        public string AltCode { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string EDISenderID { get; set; }
        public string EDISenderIDQualifier { get; set; }
        public string EDISenderIDQualifierGLU { get; set; }
        public byte PICountDays { get; set; }
        public bool SmallFormat { get; set; }
        public bool FulfillsCustomerOrders { get; set; }
        public string DefaultTaxCode { get; set; }
        public bool ShipSunday { get; set; }
        public bool ShipMonday { get; set; }
        public bool ShipTuesday { get; set; }
        public bool ShipWednesday { get; set; }
        public bool ShipThursday { get; set; }
        public bool ShipFriday { get; set; }
        public bool ShipSaturday { get; set; }
        public bool ShipScheduleSameAsRepl { get; set; }
    
        public virtual lookupcode lookupcode { get; set; }
        public virtual lookupcode lookupcode1 { get; set; }
        public virtual lookupcode lookupcode2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<branch> branches1 { get; set; }
        public virtual branch branch1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<brnstock> brnstocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<btranshdr> btranshdrs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<btranshdr> btranshdrs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<brnstat> brnstats { get; set; }
    }
}
