//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tofscarddetails
    {
        public int Id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string postcode { get; set; }
        public string phonenumber { get; set; }
        public string email { get; set; }
        public string clubcardnumber { get; set; }
    }
}
