//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashingUpDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CashDbContext : DbContext
    {
        public CashDbContext()
            : base("name=CashDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<StoresModel> StoresModels { get; set; }
        public virtual DbSet<tbl_BankingManagement> tbl_BankingManagement { get; set; }
        public virtual DbSet<tbl_CashManagement> tbl_CashManagement { get; set; }
        public virtual DbSet<tbl_SafeManagement> tbl_SafeManagement { get; set; }
        public virtual DbSet<tbl_store_till_availabilty> tbl_store_till_availabilty { get; set; }
        public virtual DbSet<tbl_StoreDetails> tbl_StoreDetails { get; set; }
    }
}
