//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashingUpDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BankingManagement
    {
        public int RowId { get; set; }
        public string UserId { get; set; }
        public string StoredId { get; set; }
        public Nullable<decimal> VoucherAmount { get; set; }
        public Nullable<decimal> CashAmount { get; set; }
        public string InnerBag { get; set; }
        public string OuterBag { get; set; }
        public Nullable<System.DateTime> TradingDay { get; set; }
        public bool isClosed { get; set; }
        public string ClosedBy { get; set; }
        public string WitnessName { get; set; }
        public Nullable<System.DateTime> WitnessDate { get; set; }
        public bool isWitnessed { get; set; }
        public bool isDeleted { get; set; }
        public string DateDeleted { get; set; }
        public string DeletedBy { get; set; }
    }
}
