//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashingUpDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SafeManagement
    {
        public int RowId { get; set; }
        public Nullable<int> SafeId { get; set; }
        public Nullable<System.DateTime> TradingDate { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string AuthUserIdOne { get; set; }
        public string AuthUserIdTwo { get; set; }
        public string UserId { get; set; }
        public string StoreId { get; set; }
        public decimal CashAmount { get; set; }
        public decimal CardAmount { get; set; }
        public decimal GiftCardAmount { get; set; }
        public string Notes { get; set; }
        public bool isLocked { get; set; }
        public System.DateTime LockedDate { get; set; }
        public string lockedBy { get; set; }
        public bool isDeleted { get; set; }
        public string DeletedBy { get; set; }
        public bool isClosed { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
    }
}
