//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashingUpDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_store_till_availabilty
    {
        public int RowId { get; set; }
        public string storeNumber { get; set; }
        public Nullable<int> TillId { get; set; }
        public Nullable<bool> isAlive { get; set; }
        public Nullable<System.DateTime> DateTakenOffline { get; set; }
        public Nullable<bool> isSparq { get; set; }
        public Nullable<decimal> TillFloat { get; set; }
    }
}
