//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashingUpDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CashManagement
    {
        public int RowId { get; set; }
        public string StoreId { get; set; }
        public string UserId { get; set; }
        public int RJTillId { get; set; }
        public int SPQTillId { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public decimal ClosingFloat { get; set; }
        public decimal CashAmount { get; set; }
        public Nullable<decimal> Love2Shop { get; set; }
        public decimal GiftVoucherTotal { get; set; }
        public decimal CreditCardTotal { get; set; }
        public Nullable<decimal> Income { get; set; }
        public Nullable<decimal> DeliverySales { get; set; }
        public Nullable<decimal> Expense { get; set; }
        public bool isLocked { get; set; }
        public string SubmittedBy { get; set; }
        public Nullable<System.DateTime> LockedDateTime { get; set; }
        public string LockedBy { get; set; }
        public bool isDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> TradingDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> tillisLive { get; set; }
        public Nullable<bool> isClosed { get; set; }
        public Nullable<bool> isEndOfDay { get; set; }
        public Nullable<System.DateTime> ClosingDateTime { get; set; }
        public Nullable<bool> isSparq { get; set; }
        public Nullable<decimal> expectedAmount { get; set; }
        public Nullable<decimal> LSVexpectedAmount { get; set; }
        public Nullable<decimal> LSVdiscrepancyAmount { get; set; }
        public Nullable<decimal> discrepencyAmount { get; set; }
        public Nullable<bool> isLSVdiscrepancy { get; set; }
        public Nullable<bool> isDescrepency { get; set; }
        public Nullable<decimal> netSales { get; set; }
        public Nullable<decimal> marketing1100 { get; set; }
        public Nullable<decimal> lottery1101 { get; set; }
        public Nullable<decimal> parking1102 { get; set; }
        public Nullable<decimal> postage1103 { get; set; }
        public Nullable<decimal> windows1104 { get; set; }
        public Nullable<decimal> personalvehicle1105 { get; set; }
        public Nullable<decimal> carhire1106 { get; set; }
        public Nullable<decimal> publictransport1107 { get; set; }
        public Nullable<decimal> bankcharge1108 { get; set; }
        public Nullable<decimal> milk1109 { get; set; }
        public Nullable<decimal> customerservice1126 { get; set; }
        public Nullable<decimal> tofsclubcard1198 { get; set; }
        public Nullable<decimal> wages1116 { get; set; }
    }
}
