//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PICountDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sku_count
    {
        public int rowId { get; set; }
        public Nullable<int> list_id { get; set; }
        public string variantcode { get; set; }
        public Nullable<int> expected_qty { get; set; }
        public string storeId { get; set; }
    }
}
