using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace tfs_api.query.data.Models
{
    public class ProductCodeDto
    {
        public string variantcode { get; set; }
        public int prodint { get; set; }
        public int varint { get; set; }
        public string vatcode { get; set; }
        public Nullable<double> repcost { get; set; }
        public string status { get; set; }
        public string baseproduct { get; set; }
        public string sequenceno { get; set; }
        public string varcode1 { get; set; }
        public string varcode2 { get; set; }
        public string vardesc1 { get; set; }
        public string vardesc2 { get; set; }
        public string SeasonIntroduced { get; set; }
        public string CoordinateGroup { get; set; }
        public string Silhouette { get; set; }
        public string InventoryStatus { get; set; }
        public string CountryOrigin { get; set; }
        public string CountryMfr { get; set; }
        public string CountryDispatch { get; set; }
        public string pa01 { get; set; }
        public string pa02 { get; set; }
        public string pa03 { get; set; }
        public string pa04 { get; set; }
        public string pa05 { get; set; }
        public string pa06 { get; set; }
        public string pa07 { get; set; }
        public string pa08 { get; set; }
        public string pa09 { get; set; }
        public string pa10 { get; set; }
        public string pa11 { get; set; }
        public string pa12 { get; set; }
        public string pa13 { get; set; }
        public string pa14 { get; set; }
        public string pa15 { get; set; }
        public string pa16 { get; set; }
        public string pa17 { get; set; }
        public string pa18 { get; set; }
        public string pa19 { get; set; }
        public string pa20 { get; set; }
        public string pa21 { get; set; }
        public string pa22 { get; set; }
        public string pa23 { get; set; }
        public string pa24 { get; set; }
        public string pa25 { get; set; }
        public bool CreatedOffline { get; set; }
        public Nullable<int> DefaultVendorProductID { get; set; }
        public bool Web { get; set; }
        public Nullable<int> prodint2 { get; set; }
        public bool WebRejected { get; set; }
        public Nullable<int> ClusterID { get; set; }
        public Nullable<int> WIPClusterID { get; set; }
        public Nullable<int> TargetYrWeek { get; set; }
        public string AdCode { get; set; }
        public string POSMarkdown { get; set; }
        public Nullable<System.DateTime> MarkdownDate { get; set; }
        public Nullable<int> MergeID { get; set; }
        public Nullable<System.DateTime> MergeDate { get; set; }
        public string MergeUser { get; set; }
        public string ColourARGB { get; set; }
        public string SizeType { get; set; }
        public string SizeCode { get; set; }
        public string SizeDesc { get; set; }
        public Nullable<int> ProductOptionID { get; set; }
        public string ProductOptionCode { get; set; }
        public string CouponFamily1 { get; set; }
        public string CouponFamily2 { get; set; }
        public string pa26 { get; set; }
        public string pa27 { get; set; }
        public string pa28 { get; set; }
        public string pa29 { get; set; }
        public string pa30 { get; set; }
        public string pa31 { get; set; }
        public string pa32 { get; set; }
        public string pa33 { get; set; }
        public string pa34 { get; set; }
        public string pa35 { get; set; }
        public string pa36 { get; set; }
        public string pa37 { get; set; }
        public string pa38 { get; set; }
        public string pa39 { get; set; }
        public string pa40 { get; set; }
        public string pa41 { get; set; }
        public string pa42 { get; set; }
        public string pa43 { get; set; }
        public string pa44 { get; set; }
        public string pa45 { get; set; }
        public string pa46 { get; set; }
        public string pa47 { get; set; }
        public string pa48 { get; set; }
        public string pa49 { get; set; }
        public string pa50 { get; set; }
        public string pa51 { get; set; }
        public string pa52 { get; set; }
        public string pa53 { get; set; }
        public string pa54 { get; set; }
        public string pa55 { get; set; }
        public string pa56 { get; set; }
        public string pa57 { get; set; }
        public string pa58 { get; set; }
        public string pa59 { get; set; }
        public string pa60 { get; set; }
        public string pa61 { get; set; }
        public string pa62 { get; set; }
        public string pa63 { get; set; }
        public string pa64 { get; set; }
        public string pa65 { get; set; }
        public string pa66 { get; set; }
        public string pa67 { get; set; }
        public string pa68 { get; set; }
        public string pa69 { get; set; }
        public string pa70 { get; set; }
        public string pa71 { get; set; }
        public string pa72 { get; set; }
        public string pa73 { get; set; }
        public string pa74 { get; set; }
        public string pa75 { get; set; }
        public string pa76 { get; set; }
        public string pa77 { get; set; }
        public string pa78 { get; set; }
        public string pa79 { get; set; }
        public string pa80 { get; set; }
        public string pa81 { get; set; }
        public string pa82 { get; set; }
        public string pa83 { get; set; }
        public string pa84 { get; set; }
        public string pa85 { get; set; }
        public string pa86 { get; set; }
        public string pa87 { get; set; }
        public string pa88 { get; set; }
        public string pa89 { get; set; }
        public string pa90 { get; set; }
        public string pa91 { get; set; }
        public string pa92 { get; set; }
        public string pa93 { get; set; }
        public string pa94 { get; set; }
        public string pa95 { get; set; }
        public string pa96 { get; set; }
        public string pa97 { get; set; }
        public string pa98 { get; set; }
        public string pa99 { get; set; }

    }
}
