//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mi9DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Mi9DBEntities : DbContext
    {
        public Mi9DBEntities()
            : base("name=Mi9DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<altdesc> altdescs { get; set; }
        public virtual DbSet<lookupcode> lookupcodes { get; set; }
        public virtual DbSet<prodkey> prodkeys { get; set; }
        public virtual DbSet<productcode> productcodes { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<feature> features { get; set; }
        public virtual DbSet<TOFS_RetailPrice> TOFS_RetailPrice { get; set; }
        public virtual DbSet<supplier> suppliers { get; set; }
        public virtual DbSet<supproduct> supproducts { get; set; }
        public virtual DbSet<brnstock> brnstocks { get; set; }
        public virtual DbSet<structlevel> structlevels { get; set; }
        public virtual DbSet<btranshdr> btranshdrs { get; set; }
        public virtual DbSet<btransline> btranslines { get; set; }
        public virtual DbSet<fiscperiod> fiscperiods { get; set; }
        public virtual DbSet<branch> branches { get; set; }
        public virtual DbSet<brnstat> brnstats { get; set; }
        public virtual DbSet<consigdest> consigdests { get; set; }
        public virtual DbSet<consighdr> consighdrs { get; set; }
        public virtual DbSet<consigline> consiglines { get; set; }
        public virtual DbSet<purchorder> purchorders { get; set; }
        public virtual DbSet<purchordline> purchordlines { get; set; }
        public virtual DbSet<statuscode> statuscodes { get; set; }
        public virtual DbSet<tfs_store_details> tfs_store_details { get; set; }
        public virtual DbSet<tfs_stockhome_feedback> tfs_stockhome_feedback { get; set; }
        public virtual DbSet<whstock> whstocks { get; set; }
        public virtual DbSet<whloc> whlocs { get; set; }
        public virtual DbSet<TOFS_CostPrice> TOFS_CostPrice { get; set; }
        public virtual DbSet<TFS_Store_Updated> TFS_Store_Updated { get; set; }
        public virtual DbSet<rpricehdr> rpricehdrs { get; set; }
        public virtual DbSet<rpricehist> rpricehists { get; set; }
    }
}
