//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickAndCollectDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CCDBContext : DbContext
    {
        public CCDBContext()
            : base("name=CCDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClickAndCollectProduct> ClickAndCollectProducts { get; set; }
        public virtual DbSet<ClickAndCollectReservation> ClickAndCollectReservations { get; set; }
        public virtual DbSet<ClickAndCollectReservationStatu> ClickAndCollectReservationStatus { get; set; }
        public virtual DbSet<ClickAndCollectMessage> ClickAndCollectMessages { get; set; }
        public virtual DbSet<ClickAndCollectProductTranslation> ClickAndCollectProductTranslations { get; set; }
    }
}
