//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPARQTestDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SparqTestDbContext : DbContext
    {
        public SparqTestDbContext()
            : base("name=SparqTestDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Sparq_QueBuster_BasketDetails> tbl_Sparq_QueBuster_BasketDetails { get; set; }
        public virtual DbSet<tbl_Sparq_QueueBuster_CardDetails> tbl_Sparq_QueueBuster_CardDetails { get; set; }
    }
}
