//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPARQTestDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Sparq_QueueBuster_CardDetails
    {
        public int RowId { get; set; }
        public string cardnumber { get; set; }
        public System.DateTime scandate { get; set; }
        public bool isOpen { get; set; }
    }
}
