//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuditDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_audit_api
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string StoreId { get; set; }
        public string SKU { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public Nullable<int> StockAdjustLevel { get; set; }
        public Nullable<decimal> RetailValue { get; set; }
        public Nullable<decimal> CostValue { get; set; }
        public Nullable<int> PriorResonCode { get; set; }
        public string PriorStatusCode { get; set; }
        public Nullable<int> EventType { get; set; }
        public string Area { get; set; }
        public string condignment { get; set; }
        public string recordId { get; set; }
        public Nullable<int> condestint { get; set; }
        public Nullable<int> goodsout_sku_qty { get; set; }
        public string destinationstoreid { get; set; }
        public Nullable<int> controllerarea { get; set; }
    }
}
