//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuditDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PP_frontend_audit
    {
        public int rowid { get; set; }
        public string userid { get; set; }
        public System.DateTime eventdate { get; set; }
        public string previousstatuscode { get; set; }
        public Nullable<decimal> previouscost { get; set; }
        public Nullable<int> previousqty { get; set; }
        public Nullable<decimal> previousthreshold { get; set; }
    }
}
