//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuditDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_writeoff_audit
    {
        public int rowid { get; set; }
        public System.DateTime DateofWriteOff { get; set; }
        public string userid { get; set; }
        public string sku { get; set; }
        public string storeid { get; set; }
        public int varint { get; set; }
        public int stockleveldifference { get; set; }
        public int writeofftotalqty { get; set; }
        public decimal costvalue { get; set; }
        public Nullable<decimal> writeofftotalcost { get; set; }
        public System.DateTime eventdate { get; set; }
        public string reasonCode { get; set; }
        public string descriptions { get; set; }
        public Nullable<decimal> retailperitem { get; set; }
        public Nullable<decimal> retailvaluetotal { get; set; }
        public string reasoncodeDescription { get; set; }
    }
}
