//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mi9TESTDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class structlevel
    {
        public string level1 { get; set; }
        public string level2 { get; set; }
        public string level3 { get; set; }
        public string description { get; set; }
        public string shortdesc { get; set; }
        public string vatcode { get; set; }
        public string historylevel { get; set; }
        public string orderind { get; set; }
        public string autoallocate { get; set; }
        public Nullable<double> mingmpc { get; set; }
        public Nullable<double> maxgmpc { get; set; }
        public string costmethod { get; set; }
        public string issuemethod { get; set; }
        public string salesnomcode { get; set; }
        public string purchnomcode { get; set; }
        public string stocknomcode { get; set; }
        public string purchunits { get; set; }
        public string stockunits { get; set; }
        public string salesunits { get; set; }
        public string supplier { get; set; }
        public string buyer { get; set; }
        public string abccode { get; set; }
        public string disccat { get; set; }
        public string commcat { get; set; }
        public string seasoncode { get; set; }
        public string resprodcode { get; set; }
        public string distplan { get; set; }
        public string forecast { get; set; }
        public string suppriority { get; set; }
        public string surcharge { get; set; }
        public string merchmodel { get; set; }
        public string carrmethod { get; set; }
        public string carrcharge { get; set; }
        public string misccharge { get; set; }
        public string handling { get; set; }
        public string prodstruct { get; set; }
        public string vartable1 { get; set; }
        public string vartable2 { get; set; }
        public string dummyind { get; set; }
        public Nullable<int> hitcount { get; set; }
        public Nullable<int> popcount { get; set; }
        public Nullable<System.DateTime> amenddate { get; set; }
        public System.DateTime createdate { get; set; }
        public Nullable<System.DateTime> deletedate { get; set; }
        public string deleteind { get; set; }
        public Nullable<System.DateTime> accessdate { get; set; }
        public string convcode { get; set; }
        public int levint { get; set; }
        public string priceband { get; set; }
        public string gradetable { get; set; }
        public string keydatetype { get; set; }
        public string replenmethod { get; set; }
        public Nullable<double> wksstockheld { get; set; }
        public Nullable<short> backsalhist { get; set; }
        public Nullable<int> dumpvarint { get; set; }
        public string featsetcode { get; set; }
        public string vargroup1 { get; set; }
        public string vargroup2 { get; set; }
        public string customsdesc { get; set; }
        public string primarymaterial { get; set; }
        public string countrymfr { get; set; }
        public Nullable<decimal> cubefactor { get; set; }
        public Nullable<decimal> weight { get; set; }
        public string prodclass { get; set; }
        public string LabelType { get; set; }
        public bool Consignment { get; set; }
        public string level4 { get; set; }
        public string level5 { get; set; }
        public Nullable<int> ProductClusterGroupID { get; set; }
        public Nullable<int> MHClusterGroupID { get; set; }
        public Nullable<int> ClusterID { get; set; }
        public string AllocUnits { get; set; }
        public string ProductAttributeSetCode { get; set; }
        public Nullable<decimal> RetailCostMultiplier { get; set; }
        public string ExpenseItemReasonGLU { get; set; }
        public string ExpenseItemReason { get; set; }
        public string CountryOrigin { get; set; }
        public string CountryGLU { get; set; }
        public Nullable<bool> Replenished { get; set; }
    
        public virtual supplier supplier1 { get; set; }
    }
}
