//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mi9DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class altdesc
    {
        public string languageid { get; set; }
        public int levint { get; set; }
        public short usageind { get; set; }
        public string description { get; set; }
        public int ID { get; set; }
        public bool CreatedOffline { get; set; }
    }
}
