//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mi9TESTDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class brnstkchk
    {
        public int levint { get; set; }
        public int prodint { get; set; }
        public int planint { get; set; }
        public string status { get; set; }
        public System.DateTime requestdate { get; set; }
        public Nullable<System.DateTime> completedate { get; set; }
    
        public virtual product product { get; set; }
    }
}
