//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessedDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchorder
    {
        public Nullable<int> suppint { get; set; }
        public string ordernumber { get; set; }
        public Nullable<System.DateTime> orderdate { get; set; }
        public Nullable<short> status { get; set; }
        public Nullable<int> transint { get; set; }
        public Nullable<System.DateTime> shipdate { get; set; }
        public string location { get; set; }
        public Nullable<System.DateTime> lastdeldate { get; set; }
    }
}
