//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessedDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PP_ThresholdValues
    {
        public int rowId { get; set; }
        public decimal thresholdvalue { get; set; }
        public string createdby { get; set; }
        public System.DateTime datecreated { get; set; }
        public Nullable<System.DateTime> dateupdated { get; set; }
        public string updatedby { get; set; }
        public bool isInUse { get; set; }
    }
}
