//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessedDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOFS_12WeeksSales
    {
        public int rowId { get; set; }
        public string branchcode { get; set; }
        public Nullable<int> varint { get; set; }
        public string salesweek { get; set; }
        public Nullable<int> Sales { get; set; }
    }
}
