//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mi9TESTDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class supproduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public supproduct()
        {
            this.productcodes = new HashSet<productcode>();
            this.purchordlines = new HashSet<purchordline>();
            this.supproducts1 = new HashSet<supproduct>();
            this.supprodunits = new HashSet<supprodunit>();
        }
    
        public int suppint { get; set; }
        public string supproduct1 { get; set; }
        public int supprodint { get; set; }
        public Nullable<int> prodint { get; set; }
        public Nullable<int> varint { get; set; }
        public string description { get; set; }
        public string reference { get; set; }
        public string anacode { get; set; }
        public Nullable<decimal> retailprice { get; set; }
        public string rrpvat { get; set; }
        public string vatcode { get; set; }
        public string convcode { get; set; }
        public string salesunits { get; set; }
        public Nullable<int> minorder { get; set; }
        public Nullable<int> maxorder { get; set; }
        public Nullable<int> minvalue { get; set; }
        public Nullable<int> maxvalue { get; set; }
        public Nullable<short> minlead { get; set; }
        public Nullable<short> maxlead { get; set; }
        public Nullable<short> leadtimetype { get; set; }
        public Nullable<short> life { get; set; }
        public string origin { get; set; }
        public short preference { get; set; }
        public Nullable<int> suppbrint { get; set; }
        public Nullable<System.DateTime> introdate { get; set; }
        public Nullable<System.DateTime> discondate { get; set; }
        public string suspreason { get; set; }
        public Nullable<System.DateTime> suspdate { get; set; }
        public string suspuser { get; set; }
        public Nullable<System.DateTime> reinstdate { get; set; }
        public string reinstuser { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> amenddate { get; set; }
        public Nullable<System.DateTime> deletedate { get; set; }
        public short status { get; set; }
        public Nullable<double> discount { get; set; }
        public string settletype { get; set; }
        public Nullable<int> mindelqty { get; set; }
        public Nullable<int> maxdelqty { get; set; }
        public Nullable<int> mindelval { get; set; }
        public Nullable<int> maxdelval { get; set; }
        public string bandingunits { get; set; }
        public Nullable<short> sourcepercent { get; set; }
        public bool CreatedOffline { get; set; }
        public string vardesc1 { get; set; }
        public string vardesc2 { get; set; }
        public Nullable<int> basesupprodint { get; set; }
        public Nullable<int> OrderMultiple { get; set; }
        public string ImportCertificate { get; set; }
        public Nullable<System.DateTime> ImportCertificateStartDate { get; set; }
        public Nullable<System.DateTime> ImportCertificateEndDate { get; set; }
        public bool ImportCertificateInProgress { get; set; }
        public string SafetyCertificate { get; set; }
        public string UserCreated { get; set; }
        public string UserAmended { get; set; }
        public string CountryMfr { get; set; }
        public string CountryDispatch { get; set; }
        public bool Active { get; set; }
        public string UserActiveChanged { get; set; }
        public Nullable<System.DateTime> DateActiveChanged { get; set; }
        public Nullable<System.DateTime> DateLastModified { get; set; }
        public int AvailableForWebFF { get; set; }
    
        public virtual productcode productcode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productcode> productcodes { get; set; }
        public virtual product product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchordline> purchordlines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<supproduct> supproducts1 { get; set; }
        public virtual supproduct supproduct2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<supprodunit> supprodunits { get; set; }
    }
}
