//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickAndCollectDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClickAndCollectReservationStatu
    {
        public long ReservationID { get; set; }
        public int ReservationStatus { get; set; }
        public System.DateTime StatusDate { get; set; }
        public int PreviousStatus { get; set; }
        public string LastAction { get; set; }
        public string BasketTransActionId { get; set; }
        public byte[] RowVersion { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string StoreId { get; set; }
    }
}
