//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickAndCollectDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClickAndCollectReservation
    {
        public long ReservationID { get; set; }
        public string StoreNumber { get; set; }
        public string SKU { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string CustFirstName { get; set; }
        public string CustSurName { get; set; }
        public string CustPostCode { get; set; }
        public string CustEmailAddress { get; set; }
        public string TofsCardNumber { get; set; }
        public string CustMobileNumber { get; set; }
        public bool MarketingConsent { get; set; }
        public Nullable<System.DateTime> MarketingConsentDate { get; set; }
        public Nullable<System.DateTime> TermsAndCondsConsentDate { get; set; }
    }
}
