//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mi9DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOFS_CostPrice
    {
        public string prodcode { get; set; }
        public int prodint { get; set; }
        public Nullable<double> Cost { get; set; }
        public string currency { get; set; }
    }
}
