//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErrorViewDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExceptionDetail
    {
        public int RowID { get; set; }
        public System.DateTime ExceptionDate { get; set; }
        public string InnerException { get; set; }
        public string StackTrace { get; set; }
        public string Area { get; set; }
        public string Message { get; set; }
        public string User { get; set; }
    }
}
