//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mi9DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tfs_store_details
    {
        public int RowId { get; set; }
        public string storeId { get; set; }
        public Nullable<decimal> properties_long { get; set; }
        public Nullable<decimal> properties_lat { get; set; }
        public string store_name { get; set; }
        public string store_address { get; set; }
        public Nullable<bool> isMeraki { get; set; }
        public Nullable<int> area { get; set; }
        public string email { get; set; }
        public string postcode { get; set; }
    }
}
