//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mi9DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class brnstat
    {
        public short yearno { get; set; }
        public short period { get; set; }
        public string branchcode { get; set; }
        public int prodint { get; set; }
        public short @class { get; set; }
        public decimal costvalue { get; set; }
        public decimal retailvalue { get; set; }
        public int quantity { get; set; }
        public Nullable<double> taxvalue { get; set; }
        public Nullable<int> YrPeriod { get; set; }
    
        public virtual branch branch { get; set; }
        public virtual productcode productcode { get; set; }
    }
}
