//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mi9DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class consigline
    {
        public int condestint { get; set; }
        public int transline { get; set; }
        public int conlineint { get; set; }
        public string destordref { get; set; }
        public Nullable<int> destordline { get; set; }
        public Nullable<int> destordint { get; set; }
        public int varint { get; set; }
        public Nullable<int> batchint { get; set; }
        public int issueqty { get; set; }
        public Nullable<int> receiveqty { get; set; }
        public double avcost { get; set; }
        public Nullable<decimal> unitretail { get; set; }
        public Nullable<decimal> othervalue { get; set; }
        public Nullable<int> discrepqty { get; set; }
        public short download { get; set; }
        public int RequestQty { get; set; }
        public string ReasonCode { get; set; }
        public Nullable<int> WIPQty { get; set; }
        public Nullable<int> InTransitQuantity { get; set; }
        public int PackedQty { get; set; }
        public Nullable<decimal> DestLocAverageCost { get; set; }
        public Nullable<decimal> DestLocUnitPrice { get; set; }
    
        public virtual productcode productcode { get; set; }
    }
}
