//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mi9DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class feature
    {
        public int sourceint { get; set; }
        public string typecode { get; set; }
        public string feature1 { get; set; }
        public string featureset { get; set; }
        public string property { get; set; }
        public int sequenceno { get; set; }
    
        public virtual lookupcode lookupcode { get; set; }
    }
}
