//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mi9DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class fiscperiod
    {
        public System.DateTime startdate { get; set; }
        public System.DateTime enddate { get; set; }
        public string typecode { get; set; }
        public short fiscalperiod { get; set; }
        public int fiscalyear { get; set; }
        public string description { get; set; }
        public string periodtype { get; set; }
        public bool closed { get; set; }
        public bool CloseRequested { get; set; }
        public bool ExtractedToGL { get; set; }
        public string UserCloseRequested { get; set; }
        public Nullable<System.DateTime> DateCloseRequested { get; set; }
    }
}
