//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mi9DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class lookupcode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lookupcode()
        {
            this.features = new HashSet<feature>();
            this.suppliers = new HashSet<supplier>();
            this.suppliers1 = new HashSet<supplier>();
            this.suppliers2 = new HashSet<supplier>();
            this.suppliers3 = new HashSet<supplier>();
            this.structlevels = new HashSet<structlevel>();
            this.structlevels1 = new HashSet<structlevel>();
            this.structlevels2 = new HashSet<structlevel>();
            this.branches = new HashSet<branch>();
            this.branches1 = new HashSet<branch>();
            this.branches2 = new HashSet<branch>();
            this.consigdests = new HashSet<consigdest>();
            this.consighdrs = new HashSet<consighdr>();
            this.purchorders = new HashSet<purchorder>();
            this.purchorders1 = new HashSet<purchorder>();
            this.purchorders2 = new HashSet<purchorder>();
            this.purchorders3 = new HashSet<purchorder>();
            this.purchorders4 = new HashSet<purchorder>();
            this.purchorders5 = new HashSet<purchorder>();
            this.purchorders6 = new HashSet<purchorder>();
        }
    
        public string codetype { get; set; }
        public string code { get; set; }
        public string description { get; set; }
        public string shortdesc { get; set; }
        public string auxvalue1 { get; set; }
        public string auxvalue2 { get; set; }
        public Nullable<double> floatvalue { get; set; }
        public Nullable<int> intvalue { get; set; }
        public string inviolate { get; set; }
        public int notepad { get; set; }
        public string AuxValue3 { get; set; }
        public string AuxValue4 { get; set; }
        public string AuxValue5 { get; set; }
        public Nullable<double> FloatValue2 { get; set; }
        public Nullable<double> FloatValue3 { get; set; }
        public Nullable<int> IntValue2 { get; set; }
        public Nullable<int> IntValue3 { get; set; }
        public string AuxValue6 { get; set; }
        public string AuxValue7 { get; set; }
        public string AuxValue8 { get; set; }
        public string AuxValue9 { get; set; }
        public string AuxValue10 { get; set; }
        public Nullable<double> FloatValue4 { get; set; }
        public Nullable<double> FloatValue5 { get; set; }
        public Nullable<int> IntValue4 { get; set; }
        public Nullable<int> IntValue5 { get; set; }
        public bool Interfaced { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<feature> features { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<supplier> suppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<supplier> suppliers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<supplier> suppliers2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<supplier> suppliers3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<structlevel> structlevels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<structlevel> structlevels1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<structlevel> structlevels2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<branch> branches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<branch> branches1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<branch> branches2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<consigdest> consigdests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<consighdr> consighdrs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchorder> purchorders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchorder> purchorders1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchorder> purchorders2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchorder> purchorders3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchorder> purchorders4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchorder> purchorders5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchorder> purchorders6 { get; set; }
    }
}
