//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mi9DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tfs_stockhome_feedback
    {
        public int RowId { get; set; }
        public string storeid { get; set; }
        public string userid { get; set; }
        public string comments { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
