//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity.ModelConfiguration;

namespace Mi9DataAccessLayer
{
    internal class TwelveWeekConfiguration : EntityTypeConfiguration<TOFS_12WeeksSales>
    {
        public TwelveWeekConfiguration()
        {
            ToTable("TOFS_12WeeksSales");
            HasKey(x => x.branchcode);
        }
    }
}