//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mi9DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class whloc
    {
        public string warehouse { get; set; }
        public string binlocation { get; set; }
        public int binint { get; set; }
        public int capacity { get; set; }
        public string capunits { get; set; }
        public int picksequence { get; set; }
        public string quartype { get; set; }
        public string bintype { get; set; }
        public short binloc1 { get; set; }
        public short binloc2 { get; set; }
        public short binloc3 { get; set; }
        public short binloc4 { get; set; }
        public string specialbin { get; set; }
        public Nullable<System.DateTime> stkchkdate { get; set; }
        public string negstock { get; set; }
        public string includeinrpl { get; set; }
        public string realbin { get; set; }
        public short typepriority { get; set; }
        public Nullable<int> ZoneID { get; set; }
        public string WmsBinLocationCode { get; set; }
    }
}
