//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mi9DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class whstock
    {
        public string warehouse { get; set; }
        public int binint { get; set; }
        public int varint { get; set; }
        public Nullable<int> batchint { get; set; }
        public int stock { get; set; }
        public Nullable<System.DateTime> lastmovedate { get; set; }
        public int allocstock { get; set; }
        public string batchesind { get; set; }
    }
}
