//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHTTaskDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tasks
    {
        public int id { get; set; }
        public string storeid { get; set; }
        public string decrption { get; set; }
        public string instructions { get; set; }
    }
}
