//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessedPalletsDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProcessedDBContext : DbContext
    {
        public ProcessedDBContext()
            : base("name=ProcessedDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<hs_processed_consighdrs> hs_processed_consighdrs { get; set; }
        public virtual DbSet<hs_processed_interstore> hs_processed_interstore { get; set; }
        public virtual DbSet<hs_processed_purchorders> hs_processed_purchorders { get; set; }
        public virtual DbSet<consighdr> consighdrs { get; set; }
        public virtual DbSet<consigdest> consigdests { get; set; }
        public virtual DbSet<consigline> consiglines { get; set; }
        public virtual DbSet<purchorder> purchorderss { get; set; }
        public virtual DbSet<purchordline> purchordliness { get; set; }
        public virtual DbSet<statuscode> statuscodes { get; set; }
        public virtual DbSet<supplier> suppliers { get; set; }
    }
}
