//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessedPalletsDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchorder
    {
        public int suppint { get; set; }
        public string ordernumber { get; set; }
        public string buyer { get; set; }
        public Nullable<int> suppbrint { get; set; }
        public string seasoncode { get; set; }
        public System.DateTime orderdate { get; set; }
        public System.DateTime createdate { get; set; }
        public Nullable<System.DateTime> amenddate { get; set; }
        public Nullable<System.DateTime> printdate { get; set; }
        public Nullable<System.DateTime> makeupdate { get; set; }
        public Nullable<System.DateTime> makeupprint { get; set; }
        public string location { get; set; }
        public Nullable<System.DateTime> deliverydate { get; set; }
        public Nullable<System.DateTime> canceldate { get; set; }
        public string ackreference { get; set; }
        public Nullable<System.DateTime> ackdate { get; set; }
        public string authuser { get; set; }
        public Nullable<System.DateTime> authdate { get; set; }
        public Nullable<int> plint { get; set; }
        public Nullable<double> settlement { get; set; }
        public string settletype { get; set; }
        public string buyingmethod { get; set; }
        public string currency { get; set; }
        public Nullable<double> currrate { get; set; }
        public string usercode { get; set; }
        public short status { get; set; }
        public int transint { get; set; }
        public Nullable<short> makeupstatus { get; set; }
        public string printprice { get; set; }
        public string openorder { get; set; }
        public short ordertype { get; set; }
        public Nullable<int> splint { get; set; }
        public Nullable<short> printstatus { get; set; }
        public string dealnumber { get; set; }
        public Nullable<int> amendno { get; set; }
        public string allowbo { get; set; }
        public Nullable<int> compafter { get; set; }
        public string channelcode { get; set; }
        public string faxsubmitref { get; set; }
        public string faxstatus { get; set; }
        public string type { get; set; }
        public Nullable<System.DateTime> shipdate { get; set; }
        public string carrier { get; set; }
        public Nullable<System.DateTime> firstdeldate { get; set; }
        public Nullable<System.DateTime> lastdeldate { get; set; }
        public bool CreatedOffline { get; set; }
        public byte SendEDI { get; set; }
        public string AmendUser { get; set; }
        public string TransportMethod { get; set; }
        public string VendorPromoCode { get; set; }
        public Nullable<int> KitAssemblyOrderID { get; set; }
        public string CheckOutUser { get; set; }
        public Nullable<System.DateTime> CheckOutDate { get; set; }
        public byte AllocStatus { get; set; }
        public string UserClosed { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public Nullable<decimal> BuyerCommissionPC { get; set; }
        public string Reference1 { get; set; }
        public decimal PriceListCurrRate { get; set; }
        public string PurchaseType { get; set; }
        public Nullable<int> YrWeek { get; set; }
        public Nullable<System.DateTime> EmailDate { get; set; }
        public int EmailCount { get; set; }
        public bool EmailFailed { get; set; }
        public string EmailFailedText { get; set; }
        public int EmailTryCount { get; set; }
        public bool ReplenishmentOrder { get; set; }
        public bool EmailAgain { get; set; }
        public Nullable<int> PurchaseContractID { get; set; }
        public string Reference2 { get; set; }
        public Nullable<System.DateTime> DateInterfaced { get; set; }
        public Nullable<System.DateTime> DateEDIFirstSent { get; set; }
        public Nullable<System.DateTime> DateEDILastSent { get; set; }
        public Nullable<int> LastEDIControlNumber { get; set; }
        public System.DateTime DoNotDeliverAfterDate { get; set; }
        public Nullable<int> VendorLocationID { get; set; }
        public Nullable<int> VMITransactionID { get; set; }
        public bool SendToPOS { get; set; }
        public Nullable<System.DateTime> DateBooked { get; set; }
        public Nullable<System.DateTime> VersionDate { get; set; }
        public string PayMethod { get; set; }
        public string PayMethodGLU { get; set; }
        public string SpecialInstructions1 { get; set; }
        public string SpecialInstructions2 { get; set; }
        public string SpecialInstructionsGLU { get; set; }
        public string ShippingInstructions { get; set; }
        public string ShippingInstructionsGLU { get; set; }
        public string CancellationNote { get; set; }
        public decimal NewStoreCostDiscount { get; set; }
        public bool QualifiesForNewStoreDiscount { get; set; }
        public bool MergedIntoPO { get; set; }
        public string FinalLocationCode { get; set; }
        public string AckStatus { get; set; }
        public Nullable<System.DateTime> ASNFirstReceivedDate { get; set; }
        public Nullable<System.DateTime> ASNLastReceivedDate { get; set; }
        public string CustomID { get; set; }
        public string ChangeReason { get; set; }
        public string ChangeReasonGLU { get; set; }
        public byte EDISentCount { get; set; }
        public System.DateTime DateLastModified { get; set; }
        public Nullable<int> CustomerOrderID { get; set; }
        public Nullable<System.DateTime> DateAmendedForEDI { get; set; }
        public string SpecialOrderStatus { get; set; }
        public string SpecialOrderStatusGLU { get; set; }
        public string SpecialOrderCancellationStatus { get; set; }
        public string SpecialOrderCancellationStatusGLU { get; set; }
        public string SpecialOrderAuthorizeCancellationNotes { get; set; }
        public string SpecialOrderAuthorizeReactivationNotes { get; set; }
        public Nullable<System.DateTime> DateAuthorizedSpecialOrderCancellation { get; set; }
        public string UserAuthorizedSpecialOrderCancellation { get; set; }
        public Nullable<System.DateTime> DateAuthorizedSpecialOrderReactivation { get; set; }
        public string UserAuthorizedSpecialOrderReactivation { get; set; }
    }
}
