//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessedPalletsDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class statuscode
    {
        public string statcode { get; set; }
        public string status { get; set; }
        public string description { get; set; }
        public string shortdesc { get; set; }
        public short intvalue { get; set; }
        public string included { get; set; }
    }
}
