//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPOSDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_gdo_numbers
    {
        public int RowId { get; set; }
        public string RandomValue { get; set; }
        public Nullable<int> storeddestination { get; set; }
        public Nullable<int> storesource { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
        public Nullable<bool> isUsed { get; set; }
        public byte[] rowVersion { get; set; }
        public string generatedGDO { get; set; }
    }
}
