//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mi9TESTDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class reasoncode
    {
        public string languageid { get; set; }
        public string typecode { get; set; }
        public string reasoncode1 { get; set; }
        public string description { get; set; }
    }
}
