//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHTTaskDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaskDBContext : DbContext
    {
        public TaskDBContext()
            : base("name=TaskDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_store_responses> tbl_store_responses { get; set; }
        public virtual DbSet<tbl_tasks> tbl_tasks { get; set; }
        public virtual DbSet<tbl_task_actions> tbl_task_actions { get; set; }
        public virtual DbSet<tbl_action_types> tbl_action_types { get; set; }
    }
}
