//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mi9TESTDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class btransdisc
    {
        public int transint { get; set; }
        public int transline { get; set; }
        public short sequenceno { get; set; }
        public Nullable<int> translineint { get; set; }
        public Nullable<decimal> discountvalue { get; set; }
        public Nullable<decimal> discounttax { get; set; }
        public string reasoncode { get; set; }
        public string discountcode { get; set; }
        public string authority { get; set; }
        public int notepad { get; set; }
    }
}
