//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mi9TESTDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class supprodunit
    {
        public int supprodint { get; set; }
        public string purchunits { get; set; }
        public string anacode { get; set; }
        public short status { get; set; }
        public bool CreatedOffline { get; set; }
        public int ID { get; set; }
        public Nullable<int> ProductUnitID { get; set; }
        public bool Primary { get; set; }
        public Nullable<int> OrderMultiple { get; set; }
        public Nullable<int> MinQty { get; set; }
        public Nullable<int> MaxQty { get; set; }
        public Nullable<int> MinCost { get; set; }
        public Nullable<int> MaxCost { get; set; }
        public Nullable<int> MinWeight { get; set; }
        public Nullable<int> MaxWeight { get; set; }
        public Nullable<int> MinCube { get; set; }
        public Nullable<int> MaxCube { get; set; }
    
        public virtual supproduct supproduct { get; set; }
    }
}
