//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuditDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_goodsout_audit
    {
        public int RowId { get; set; }
        public string UserId { get; set; }
        public string StoreId { get; set; }
        public string DestinationStoreId { get; set; }
        public string Sku { get; set; }
        public Nullable<int> sku_qty { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public string consignment { get; set; }
    }
}
