//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessedPalletsDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchordline
    {
        public int transint { get; set; }
        public short transline { get; set; }
        public string location { get; set; }
        public Nullable<System.DateTime> deliverydate { get; set; }
        public Nullable<System.DateTime> canceldate { get; set; }
        public int varint { get; set; }
        public int prodint { get; set; }
        public string baseproduct { get; set; }
        public decimal quantity { get; set; }
        public int makeupqty { get; set; }
        public string purchunits { get; set; }
        public decimal unitcost { get; set; }
        public decimal netcost { get; set; }
        public decimal unitretail { get; set; }
        public string bandingunits { get; set; }
        public string packagetype { get; set; }
        public string origin { get; set; }
        public string suppprodref { get; set; }
        public string quoteref { get; set; }
        public Nullable<System.DateTime> quotedate { get; set; }
        public short status { get; set; }
        public Nullable<short> amendstatus { get; set; }
        public Nullable<short> makeupstatus { get; set; }
        public int purchlineint { get; set; }
        public Nullable<int> supprodint { get; set; }
        public Nullable<short> delschstatus { get; set; }
        public bool CreatedOffline { get; set; }
        public decimal LandedCost { get; set; }
        public decimal DutiableCost { get; set; }
        public bool MultiBrand { get; set; }
        public int BoxCount { get; set; }
        public bool PreTicket { get; set; }
        public int SampleQty { get; set; }
        public Nullable<int> YrWeek { get; set; }
        public decimal QtyPerPurchUnit { get; set; }
        public decimal QtyInPurchUnits { get; set; }
        public decimal FirstCostPerPurchUnit { get; set; }
        public Nullable<int> PurchUnitsID { get; set; }
        public decimal TaxRate { get; set; }
        public Nullable<int> MergedIntoPOLineID { get; set; }
        public Nullable<int> CustomerOrderLineID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateAmendedForEDI { get; set; }
        public Nullable<System.DateTime> DateReopened { get; set; }
        public Nullable<decimal> QtyFromEDILastSent { get; set; }
        public string SpecialOrderDescription { get; set; }
    }
}
