//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mi9TESTDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class pricechghdr
    {
        public string pricechgcode { get; set; }
        public string description { get; set; }
        public int pricechgint { get; set; }
        public System.DateTime startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public System.DateTime createdate { get; set; }
        public Nullable<System.DateTime> authdate { get; set; }
        public string reasoncode { get; set; }
        public string pricechgtype { get; set; }
        public short status { get; set; }
        public string usercode { get; set; }
        public string authuser { get; set; }
        public string buyer { get; set; }
        public Nullable<decimal> totvalue { get; set; }
        public string frequency { get; set; }
        public string daysofweek { get; set; }
        public string starttime { get; set; }
        public string endtime { get; set; }
        public Nullable<int> budgetqty { get; set; }
        public Nullable<decimal> budgetval { get; set; }
        public string eventcode { get; set; }
        public string buycond { get; set; }
        public string reccond { get; set; }
        public string disctype { get; set; }
    }
}
